-   repo: git@github.com:hootsuite/pre-commit-php.git
    sha: 1.2.0
    hooks:
    -   id: php-lint
    -   id: php-unit
-   repo: git://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: end-of-file-fixer
